services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\FileSystem\MasterImageHandlerInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\FileSystem\MasterImageHandler
    arguments:
      - "@oxid_esales.symfony.file_system"

  OxidEsales\EshopCommunity\Internal\Framework\FileSystem\Bridge\MasterImageHandlerBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\FileSystem\Bridge\MasterImageHandlerBridge
    public: true
